-- exec GetStudents --// получить всех студентов
-- exec AddNewStudent 'Имя', 'Фамилия', 0.00 --// Добавить нового студента
-- exec RemoveStudents --// Очистка таблицы студентов
-- exec GetByIdStudent 5 --// получить студента по id