-- exec GetStudents --// получить всех студентов
-- exec AddNewStudent N'Имя', 'Фамилия', 0.00 --// Добавить нового студента
-- exec RemoveStudents --// Очистка таблицы студентов
-- exec GetByIdStudent 5 --// получить студента по id
-- exec CreateNewHomeworks UMLdiagramma --// создать новое дз
  -- exec AddNewTeam 'Team1'
  -- exec GetTeams 
  -- exec GetTeamById 1
  -- exec RemoveTeamById 1
  -- exec UpdateTeamById 2, 'Team2'